# Generated by Django 4.1.3 on 2025-05-10 07:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language_app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('has_given_feedback', models.BooleanField(default=False)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('autoplay_enabled', models.BooleanField(default=True)),
                ('narration_speed', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(1.2), django.core.validators.MinValueValidator(0.8)])),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('avatar_id', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('last_current_language', models.CharField(default='fr', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word_de', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language_app.deworddata')),
                ('word_fr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language_app.frworddata')),
                ('word_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language_app.ruworddata')),
                ('word_th', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language_app.thworddata')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='following',
            field=models.ManyToManyField(related_name='followed_by', through='api.UserFollow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='known_languages',
            field=models.ManyToManyField(blank=True, to='language_app.language'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='known_words',
            field=models.ManyToManyField(blank=True, to='api.userword'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
