# Generated by Django 4.1.3 on 2025-05-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='following',
        ),
        migrations.DeleteModel(
            name='UserFollow',
        ),
    ]
