# Generated by Django 4.1.3 on 2025-05-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_appuser_following_delete_userfollow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='streak',
        ),
    ]
