# Generated by Django 4.1.3 on 2023-11-01 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_appuser_username_userfollow_appuser_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollow',
            name='following',
        ),
        migrations.RemoveField(
            model_name='userfollow',
            name='user',
        ),
        migrations.AddField(
            model_name='userfollow',
            name='followee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='followee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfollow',
            name='follower',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
