# Generated by Django 4.1.3 on 2023-11-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0008_alter_frwordfrequency_rank'),
        ('api', '0003_remove_userfollow_following_remove_userfollow_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='known_words',
            field=models.ManyToManyField(to='language_app.frwordfrequency'),
        ),
    ]
