# Generated by Django 4.1.3 on 2025-05-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_appuser_streak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='autoplay_enabled',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='has_given_feedback',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='narration_speed',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='sound_enabled',
        ),
    ]
