# Generated by Django 4.1.3 on 2023-12-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0010_language'),
        ('api', '0004_appuser_known_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='known_languages',
            field=models.ManyToManyField(to='language_app.language'),
        ),
    ]
