# Generated by Django 4.1.3 on 2025-05-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_appuser_autoplay_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userword',
            name='word_de',
        ),
        migrations.RemoveField(
            model_name='userword',
            name='word_fr',
        ),
        migrations.RemoveField(
            model_name='userword',
            name='word_ru',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_current_language',
            field=models.CharField(default='th', max_length=2),
        ),
    ]
