# Generated by Django 4.1.3 on 2023-12-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0015_remove_desentence_difficulty_score_and_more'),
        ('api', '0007_rename_known_words_appuser_known_words_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='known_languages',
            field=models.ManyToManyField(blank=True, to='language_app.language'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='known_words_de',
            field=models.ManyToManyField(blank=True, to='language_app.deworddata'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='known_words_fr',
            field=models.ManyToManyField(blank=True, to='language_app.frworddata'),
        ),
    ]
