# Generated by Django 4.1.3 on 2024-01-06 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0019_rusentence_ruworddata'),
        ('api', '0009_appuser_known_words_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='known_words_de',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='known_words_fr',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='known_words_ru',
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word_de', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language_app.deworddata')),
                ('word_fr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language_app.frworddata')),
                ('word_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language_app.ruworddata')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='known_words',
            field=models.ManyToManyField(blank=True, to='api.userword'),
        ),
    ]
