# Generated by Django 4.1.3 on 2024-01-06 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0019_rusentence_ruworddata'),
        ('api', '0010_remove_appuser_known_words_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userword',
            name='word_de',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_app.deworddata'),
        ),
        migrations.AlterField(
            model_name='userword',
            name='word_fr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_app.frworddata'),
        ),
        migrations.AlterField(
            model_name='userword',
            name='word_ru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_app.ruworddata'),
        ),
    ]
