# Generated by Django 4.1.3 on 2024-01-07 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userword_word_de_alter_userword_word_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='known_words',
            field=models.ManyToManyField(related_name='known_by', through='api.UserWord', to=settings.AUTH_USER_MODEL),
        ),
    ]
