# Generated by Django 4.1.3 on 2024-01-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_appuser_known_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
