# Generated by Django 4.1.3 on 2024-04-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_appuser_avatar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
