# Generated by Django 4.1.3 on 2024-05-03 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0023_thsentence_thworddata'),
        ('api', '0017_appuser_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='word_th',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language_app.thworddata'),
        ),
    ]
