# Generated by Django 4.1.3 on 2024-06-02 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_userword_word_th'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='autoplay_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='has_given_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='narration_speed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='appuser',
            name='sound_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
