# Generated by Django 4.1.3 on 2024-06-02 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_appuser_autoplay_enabled_appuser_has_given_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='narration_speed',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(1.2), django.core.validators.MinValueValidator(0.8)]),
        ),
    ]
