# Generated by Django 4.1.3 on 2025-05-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(null=True)),
                ('split_sentence', models.JSONField(null=True)),
                ('translated_sentence', models.TextField(null=True)),
                ('cluster', models.IntegerField(null=True)),
                ('words', models.JSONField(null=True)),
                ('average_count', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('min_count', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('average_count_rank', models.DecimalField(decimal_places=1, max_digits=20, null=True)),
                ('min_count_rank', models.DecimalField(decimal_places=1, max_digits=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeWordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('word', models.TextField(null=True)),
                ('translation', models.TextField(null=True)),
                ('frequency', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FrSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(null=True)),
                ('split_sentence', models.JSONField(null=True)),
                ('translated_sentence', models.TextField(null=True)),
                ('cluster', models.IntegerField(null=True)),
                ('words', models.JSONField(null=True)),
                ('average_count', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('min_count', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('average_count_rank', models.DecimalField(decimal_places=1, max_digits=20, null=True)),
                ('min_count_rank', models.DecimalField(decimal_places=1, max_digits=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrWordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('word', models.TextField(null=True)),
                ('translation', models.TextField(null=True)),
                ('frequency', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.TextField()),
                ('language_name', models.TextField()),
                ('coeffs', models.JSONField(default=[0, 0, 0, 0])),
            ],
        ),
        migrations.CreateModel(
            name='RuSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(null=True)),
                ('split_sentence', models.JSONField(null=True)),
                ('translated_sentence', models.TextField(null=True)),
                ('cluster', models.IntegerField(null=True)),
                ('words', models.JSONField(null=True)),
                ('average_count', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('min_count', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('average_count_rank', models.DecimalField(decimal_places=1, max_digits=20, null=True)),
                ('min_count_rank', models.DecimalField(decimal_places=1, max_digits=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuWordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('word', models.TextField(null=True)),
                ('translation', models.TextField(null=True)),
                ('frequency', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('suggestion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(null=True)),
                ('split_sentence', models.JSONField(null=True)),
                ('translated_sentence', models.TextField(null=True)),
                ('cluster', models.IntegerField(null=True)),
                ('words', models.JSONField(null=True)),
                ('average_count', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('min_count', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('average_count_rank', models.DecimalField(decimal_places=1, max_digits=20, null=True)),
                ('min_count_rank', models.DecimalField(decimal_places=1, max_digits=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThWordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('word', models.TextField(null=True)),
                ('translation', models.TextField(null=True)),
                ('frequency', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
