# Generated by Django 4.2.4 on 2023-08-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ru_Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.TextField()),
                (
                    "difficulty_score",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
            ],
        ),
    ]
