# Generated by Django 4.1.3 on 2023-11-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frsentence',
            name='difficulty_score',
        ),
        migrations.AddField(
            model_name='frsentence',
            name='average_count',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='frsentence',
            name='average_count_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='frsentence',
            name='cluster',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='frsentence',
            name='min_count',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='frsentence',
            name='min_count_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='frsentence',
            name='words',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='frsentence',
            name='sentence',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='frsentence',
            name='translated_sentence',
            field=models.TextField(null=True),
        ),
    ]
