# Generated by Django 4.2.4 on 2023-08-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("language_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Ru_Sentence", new_name="RuSentence",),
    ]
