# Generated by Django 4.1.3 on 2025-05-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
