# Generated by Django 4.1.3 on 2023-09-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0002_rename_ru_sentence_rusentence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RuSentence',
            new_name='FrSentence',
        ),
    ]
