# Generated by Django 4.1.3 on 2025-05-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_userword_word_de_remove_userword_word_fr_and_more'),
        ('language_app', '0002_delete_faq_delete_suggestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeSentence',
        ),
        migrations.DeleteModel(
            name='DeWordData',
        ),
        migrations.DeleteModel(
            name='FrSentence',
        ),
        migrations.DeleteModel(
            name='FrWordData',
        ),
        migrations.DeleteModel(
            name='RuSentence',
        ),
        migrations.DeleteModel(
            name='RuWordData',
        ),
    ]
