# Generated by Django 4.1.3 on 2023-11-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0002_remove_frsentence_difficulty_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frsentence',
            name='average_count_rank',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='frsentence',
            name='min_count_rank',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True),
        ),
    ]
