# Generated by Django 4.1.3 on 2023-09-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0003_rename_rusentence_frsentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='frsentence',
            name='translated_sentence',
            field=models.TextField(default='No translation'),
            preserve_default=False,
        ),
    ]
