# Generated by Django 4.1.3 on 2023-11-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0004_frwordfrequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frwordfrequency',
            name='word',
            field=models.TextField(null=True),
        ),
    ]
