# Generated by Django 4.1.3 on 2023-11-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0005_alter_frwordfrequency_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frwordfrequency',
            name='frequency',
            field=models.IntegerField(null=True),
        ),
    ]
