# Generated by Django 4.1.3 on 2023-11-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appuser_known_words'),
        ('language_app', '0008_alter_frwordfrequency_rank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrWordFrequency',
            new_name='FrWordData',
        ),
    ]
