# Generated by Django 4.1.3 on 2023-12-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0011_rename_language_language_language_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.TextField(),
        ),
    ]
