# Generated by Django 4.1.3 on 2023-12-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0015_remove_desentence_difficulty_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desentence',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='frsentence',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
