# Generated by Django 4.1.3 on 2024-01-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0019_rusentence_ruworddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='params',
            new_name='coeffs',
        ),
    ]
