# Generated by Django 4.1.3 on 2024-04-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0021_alter_desentence_words_alter_frsentence_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deworddata',
            name='translation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='frworddata',
            name='translation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ruworddata',
            name='translation',
            field=models.TextField(null=True),
        ),
    ]
