# Generated by Django 4.1.3 on 2024-05-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0022_deworddata_translation_frworddata_translation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(null=True)),
                ('translated_sentence', models.TextField(null=True)),
                ('cluster', models.IntegerField(null=True)),
                ('words', models.JSONField(null=True)),
                ('average_count', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('min_count', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('average_count_rank', models.DecimalField(decimal_places=1, max_digits=20, null=True)),
                ('min_count_rank', models.DecimalField(decimal_places=1, max_digits=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThWordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('word', models.TextField(null=True)),
                ('translation', models.TextField(null=True)),
                ('frequency', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
