# Generated by Django 4.1.3 on 2024-06-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0024_desentence_split_sentence_frsentence_split_sentence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('suggestion', models.TextField(null=True)),
            ],
        ),
    ]
