# Generated by Django 4.1.3 on 2024-06-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0025_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
