# Generated by Django 4.1.3 on 2025-01-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0026_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desentence',
            name='split_sentence',
        ),
        migrations.RemoveField(
            model_name='frsentence',
            name='split_sentence',
        ),
        migrations.RemoveField(
            model_name='rusentence',
            name='split_sentence',
        ),
        migrations.RemoveField(
            model_name='thsentence',
            name='split_sentence',
        ),
    ]
