# Generated by Django 4.1.3 on 2025-04-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0027_remove_desentence_split_sentence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desentence',
            name='split_sentence',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='frsentence',
            name='split_sentence',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='rusentence',
            name='split_sentence',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='thsentence',
            name='split_sentence',
            field=models.JSONField(null=True),
        ),
    ]
